### PR TITLE
Use Java MIDI sequencer instead of JSyn

### PR DESCRIPTION
**Pull request by daveyarwood**
Continuing from #10 / #11.

I think I may finally have this working on par with (and likely better than) the JSyn implementation. Big, big thanks to @jgkamat and @oakes for doing all of the initial legwork!

Since this is potentially a big change, I will probably make a pre-release build and post the executables here, so that we can all test it and see if there are problems, before we release it.

NB: both this PR and https://github.com/alda-lang/alda-server-clj/pull/11 will go into this next release

### CODE REVIEW

**Comment by daveyarwood** [comment]
TODO: 

- Review checklist from #11 and make sure everything we wanted to do there is accounted for.

- Make a pre-release build and post it here, have a few people with different OS's test it.

**Comment by daveyarwood** [comment]
I looked back over #11 to make sure there wasn't anything left to fix, and I think we're good to go at this point, barring any weird issues I may not have noticed yet. If there are any such issues, let's try and shake them out!

On my machine, this branch appears to be working great. I'd love to have a few other people try it and see if anything sounds or feels off at all with this new scheduler implementation based on javax.sound.midi.Sequencer, instead of JSyn.

To test:

1. Download the development build of `alda` or `alda.exe` here:

   * https://www.dropbox.com/s/pcgw9p7h51xplb2/alda?dl=0 (macOS / Linux)
   * https://www.dropbox.com/s/q7hmg6pufwc3nsq/alda.exe?dl=0 (Windows)

2. Depending on where you downloaded the executable above (I'm using `/tmp/alda` below as an example), use it to restart your Alda server:

    ```
    $ /tmp/alda downup
    ```

3. Check the output of `/tmp/alda version`. If it's 1.0.0-rc99 on both the client and server, then you're ready to test.

    ```
    $ /tmp/alda version
    Client version: 1.0.0-rc99
    Server version: [27713] 1.0.0-rc99
    ```

4. Try using `/tmp/alda` in the way that you would normally use `alda` and see if you notice any difference. Try using the REPL (`/tmp/alda repl`), playing score files (`/tmp/alda play -f somefile.alda`), etc.

If you have some time to test out this build, please comment here and let me know if you notice any differences, or if everything feels about the same as the current release of Alda. Thanks in advance for your help!

cc: @jgkamat @oakes @TBuc

**Comment by oakes** [comment]
Hey there, I've been caught up in things lately but I started testing this branch with edna a little bit. So far, direct playback seems good, but I can't get exporting to work because my code relies on the fact that `sound/create-sequence!` returns the Sequence object. It seems to return nil now. Is there any way I could get direct access to that object?

**Comment by daveyarwood** [comment]
@oakes Once the sequence is created and set in the sequencer, you should be able to [access it via the sequencer](https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/Sequencer.html#getSequence()), which is exposed in the audio context. So something like this ought to work:

```clojure
(sound/create-sequence! score)

(let [sequence (-> score :audio-context deref :midi-sequencer .getSequence)]
  ...)
```

Does that help? We _could_ modify `create-sequence!` to return the sequence, but I'd prefer not to mix for-side-effects functions with functions that return a value.

**Comment by oakes** [comment]
Ah I see, I had to manually create an :audio-context because the one created within that function is not accessible externally. So far the audio files produced are not valid but that may be my fault. I'll keep messing with it.

**Comment by oakes** [comment]
I made another sample project to make it easy to test with edna: https://github.com/oakes/new-alda-test

You'll need to install this branch locally of course, otherwise it'll use the 0.4.0 from clojars and will break. If you do `boot run` it will play the tune (but seemingly still skips the first note, unless that's just on my machine). If you do `boot build` to export to mp3, it will take a while and produce an mp3 that plays just a single note.

**Comment by daveyarwood** [comment]
@oakes I gave that project a try, but it looks like you might have a local version of Alda that's different from the one on this branch? When I tried `boot run`, I got:

```
...
                                         edna.core/play!                 core.clj:  186
                                                     ...                              
clojure.lang.ArityException: Wrong number of args (1) passed to: midi/new-midi-synth
```

And in edna.core it looks like you're calling `alda.sound.midi/new-midi-synth` (a 0-arity function) with an argument `true` or `false`.

**Comment by oakes** [comment]
Oops, you're right, that is a small change I made in my fork that isn't relevant for testing in this case. I removed the additional args. Let me know if that doesn't work.

**Comment by jgkamat** [comment]
Nice! :D

I gave this a try with all the scores I have available and this looks good to
me :)

Nice job in finishing this up, this is looking really awesome :D.

Dave Yarwood writes:

> I looked back over #11 to make sure there wasn't anything left to fix, and I think we're good to go at this point, barring any weird issues I may not have noticed yet. If there are any such issues, let's try and shake them out!
>
> On my machine, this branch appears to be working great. I'd love to have a few other people try it and see if anything sounds or feels off at all with this new scheduler implementation based on javax.sound.midi.Sequencer, instead of JSyn.
>
> To test:
>
> 1. Download the development build of `alda` or `alda.exe` here:
>
>    * https://www.dropbox.com/s/pcgw9p7h51xplb2/alda?dl=0 (macOS / Linux)
>    * https://www.dropbox.com/s/q7hmg6pufwc3nsq/alda.exe?dl=0 (Windows)
>
> 2. Depending on where you downloaded the executable above (I'm using `/tmp/alda` below as an example), use it to restart your Alda server:
>
>     ```
>     $ /tmp/alda downup
>     ```
>
> 3. Check the output of `/tmp/alda version`. If it's 1.0.0-rc99 on both the client and server, then you're ready to test.
>
>     ```
>     $ /tmp/alda version
>     Client version: 1.0.0-rc99
>     Server version: [27713] 1.0.0-rc99
>     ```
>
> 4. Try using `/tmp/alda` in the way that you would normally use `alda` and see if you notice any difference. Try using the REPL (`/tmp/alda repl`), playing score files (`/tmp/alda play -f somefile.alda`), etc.
>
> If you have some time to test out this build, please comment here and let me know if you notice any differences, or if everything feels the same as the current release of Alda. Thanks in advance for your help!
>
> cc: @jgkamat @oakes @TBuc

**Comment by daveyarwood** [comment]
@oakes When I did `boot run`, it played the first few bars of Aeris' theme, which sounded fine on my machine, which I realize isn't super helpful if you're hearing something different... but I can at least offer a couple of suggestions which might help:

1. Instead of instantiating your own MIDI synth every time, you might consider using the global sequencer and synth in `alda.sound.midi` by doing [what the Alda worker processes do](https://github.com/alda-lang/alda-server-clj/blob/a7861cbd4ee6ffbae08fbc7920bf78dfb10a2382/src/alda/worker.clj#L25-L26). The global sequencer and synth are reused for every score, which is fine if you don't need to play/export more than one score at a time.

    If you _do_ need to play/export more than one score at a time (I have a feeling that might be a requirement for midibin), then you could try leaving out the part where you bind `*midi-synth*` and/or `*midi-sequencer*` and let Alda generate them for you on the fly. To avoid hiccups, you could [pre-fill the pools by calling `fill-midi-synth-pool!` and `fill-midi-sequencer-pool!`](https://github.com/alda-lang/alda-sound-engine-clj/blob/eb528962037c4d55fba9f319ffc5561c57063eb3/src/alda/sound/midi.clj#L46-L69). I have no idea how well this will work now that we have sequencers in the mix, but I remember that the MIDI synth pool used to work pretty well back when an Alda server was just a single process that had to handle multiple scores simultaneously. I think it's worth trying if you're noticing any hiccups in your audio.

2. I think you might need to finagle the audio format settings when you're doing the MIDI -> MP3 conversion via the meico library to get the speed of playback correct. I think when I made the change from `(Sequence. Sequence/PPQ Sequence/SMPTE_24)` to `(Sequence. Sequence/SMPTE_24 2)`, that probably screwed something up in your code, which was relying on a different resolution of ticks. I think it's the case that we have a lot more ticks now, because when I ran `boot build`, it took a long time like you said, and the result was a 32 MB mp3 that appeared to be just the first chord ringing out for over an hour!

Hope this is helpful in some way. I realize I'm being a bit hand-wavy.

**Comment by oakes** [comment]
Thanks for looking into it. Disregard the first issue -- I tried it on my mac and there are no skipped notes. This only happens on my windows laptop, and apparently even happens with the current version using jsyn, so it's not related to this change. For the second, I'll try fiddling around with the parameters I pass to AudioFormat, hopefully it'll be something simple.

**Pull request merged**
